### ISSUE TITLE
milestone poll close function

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-ts#120]
- [ ] end polling after 4 days
- [ ] add to `/src/tasks` which will be scheduled once a poll begins
- [ ] count results
- [ ] update action tracking with results
- [ ] if passed set governanceCycle to current
- [ ] if failed move back to poll required
